### ISSUE TITLE
I Get Errors

### ISSUE THREAD

**Issue by yunuscatma** [chris1111/Fix-Graphics-HD-3000-Mojave-10.14-Catalina-10.15#2]
![hd3000](https://user-images.githubusercontent.com/5064386/60130601-3a49fe00-97a0-11e9-85d6-718c02ba70a2.jpg)

I installed it on a Dell N4050 (HD3000) laptop, but it remains the same as it does in the photo.

**Comment by chris1111** [comment]
Install what ? for what macOS ?

**Comment by chris1111** [comment]
Issue closed

**Comment by chris1111** [comment]
issue closed

**Comment by yunuscatma** [comment]
MY Laptop DELL N4050 (HD3000) - MACOS - High Sierra 13.6

**Comment by yunuscatma** [comment]
> Install what ? for what macOS ?

MY Laptop DELL N4050 (HD3000) - MACOS - High Sierra 13.6
